# Site configuration

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache
- about.md
- blog.md
- photos.md
- 404.md

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2
paginate_path: blog/page:num
author: Rachael Smith
google_analytics: "G-154731139"
disqus: "smithseabreeze"

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: America/New_York

# 5. Collections
collections:
  posts:
    title: Adventures Around the World
    output: true
    description: "Adventures Around the World"
    feature_image: "https://picsum.photos/1300/400?image=197"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: "posts"
    values:
      image: "https://picsum.photos/1300/400?image=195"
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

# 7. Site settings
title: "Smith Seabreeze"
description: "Smith Family in the Sunshine City!"
url: "https://smithseabreeze.com"
baseurl: ""
repo: "https://github.com/rachaelph/rachaelph.github.io"

# 8. Site favicons & manifest icons
favicons:
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: About Us
  url: /about/
- title: Blog
  url: /blog/
- title: Photos
  url: /photos/

navigation_footer:
- title: Edited by Rachael Smith
  url: https://smithseabreeze.com

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap
